<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= CONFIG_SITENAME ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <h1>Inscription</h1>
    <?php if (isset($errors) && ($errors)) : ?>
        <?php foreach ($errors as $error) : ?>
            <div class="alert alert-danger" role="alert">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
    <?php if (isset($success) && ($success)) : ?>
        <div class="alert alert-success" role="alert">
            <p> Le compte a bien été crée.</p>
        </div>
    <?php endif ?>
    <main>
        <form class="row g-3" method="POST">
            <div class="mb-3">
                <label for="inputUsername" class="form-label">Nom d'utilisateur</label>
                <input type="text" class="form-control" id="inputUsername" name="username" required>
            </div>
            <div class="mb-3">
                <label for="inputPassword" class="form-label">Mot de passe</label>
                <input type="password" class="form-control" id="inputPassword" name="password" required>
            </div>
            <div class="mb-3">
                <label for="inputEmail" class="form-label">adresse e-mail</label>
                <input type="email" class="form-control" id="inputEmail" name="email" required>
            </div>
            <button type="submit" class="btn btn-primary">S'inscrire</button>
        </form>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>